language: ruby
rvm:
  - 1.9.3
before_script:
  - psql -c 'create database twomonths_test;' -U postgres
  - "bundle exec rake db:setup"
bundler_args: --binstubs=bin/stubs
notifications:
  email: false
